CREATE DATABASE IF NOT EXISTS `usage_dashboard`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `usage_dashboard`;

CREATE TABLE IF NOT EXISTS `controletributos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `codigocontabil` varchar(255) NULL,
  `DescricaoCodigoContabil` longtext NULL,
  `MesCompetencia` int NULL,
  `AnoCompetencia` int NULL,
  `ValorPRovisaoRecolher` decimal(18,2) NULL,
  `TipoLancamentoPrevisao` varchar(50) NULL,
  `Historico` longtext NULL,
  `Vencimento` datetime(6) NULL,
  `DataRecolhimento` datetime(6) NULL,
  `ValorRecolhimento` decimal(18,2) NULL,
  `TipoLancamento` varchar(50) NULL,
  `Status` varchar(50) NULL,
  `DataCadastro` datetime(6) NULL,
  `DataAlteracao` datetime(6) NULL,
  `Ativo` tinyint(1) NULL,
  `EsteiraID` int NULL,
  `MensagemID` int NULL,
  `ChaveVinculo` varchar(50) NULL,
  `Origem` tinyint(1) NULL,
  `DataLancamento` datetime(6) NULL,
  `Regra` varchar(150) NULL,
  `TipoRegra` varchar(250) NULL,
  `SaldoInicialConta` decimal(18,2) NULL,
  `SaldoFinalConta` decimal(18,2) NULL,
  `Lancamento` varchar(250) NULL,
  `Creditos` decimal(18,2) NULL,
  `Debitos` decimal(18,2) NULL,
  `ValorPagamento` decimal(18,2) NULL,
  `ValorDesconto` decimal(18,2) NULL,
  `SaldoFinalReal` decimal(18,2) NULL,
  `LancamentoInicial` varchar(250) NULL,
  `ChaveVinculoMatch` varchar(255) NULL,
  `NovoHistorico` longtext NULL,
  `Manteve` tinyint(1) NULL DEFAULT 0,
  `HistoricoOriginal` longtext NULL,
  `CodigoContabilOriginal` varchar(255) NULL,
  `ValorAnterior` decimal(18,2) NULL,
  `ContaContraPartida` varchar(100) NULL,
  `usuarioConciliou` int NULL,
  `pontos` int NULL DEFAULT 0,
  `lancamentosRelacionados` varchar(255) NULL,
  `arquivo_id` int NULL,
  `isSaldoInicial` tinyint(1) NULL DEFAULT 0,
  `empresaId` int NULL,
  `relatorioId` int NULL,
  PRIMARY KEY (`id`),
  KEY `IX_controletributos_codigocontabil` (`codigocontabil`),
  KEY `IX_controletributos_Status` (`Status`),
  KEY `IX_controletributos_EsteiraID` (`EsteiraID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
